import type { CurriculumCourse } from '@/shared/types'

// Static curriculum data for the Faculty of Computers & AI.
// This data matches the Neo4j graph in the backend but is served as
// static frontend data — there is no student-accessible API endpoint
// for curriculum listing. The backend's /api/admin/courses is admin-only.

export const COURSES_RAW: CurriculumCourse[] = [
  { code: 'AI310', name: 'Artificial Intelligence',           credits: 3, sem: '1', prereqs: ['CS316'],        specs: ['AI','CS','IS','IT'], groups: ['AI_CORE','CS_CORE','IS_ELECTIVE','IT_CORE'] },
  { code: 'AI320', name: 'Convex Optimization Theory',        credits: 3, sem: '1', prereqs: ['MA113'],        specs: ['AI'],               groups: ['AI_CORE'] },
  { code: 'AI330', name: 'Machine Learning',                  credits: 3, sem: '1', prereqs: ['ST112'],        specs: ['AI','CS'],           groups: ['AI_CORE','CS_CORE'] },
  { code: 'AI335', name: 'Neural Networks and Deep Learning', credits: 3, sem: '1', prereqs: ['AI330'],        specs: ['AI','CS'],           groups: ['AI_CORE','CS_ELECTIVE'] },
  { code: 'AI350', name: 'Data Visualization',                credits: 3, sem: 'x', prereqs: ['ST112'],        specs: ['AI','CS'],           groups: ['AI_ELECTIVE','CS_ELECTIVE'] },
  { code: 'AI360', name: 'Natural Language Processing',       credits: 3, sem: 'x', prereqs: ['AI310'],        specs: ['AI','CS'],           groups: ['AI_CORE','CS_ELECTIVE'] },
  { code: 'AI370', name: 'Advanced Machine Learning',         credits: 3, sem: '2', prereqs: ['AI330'],        specs: ['AI'],               groups: ['AI_CORE'] },
  { code: 'AI380', name: 'Human Computer Interaction',        credits: 3, sem: 'x', prereqs: ['AI310'],        specs: ['AI','CS'],           groups: ['AI_ELECTIVE','CS_ELECTIVE'] },
  { code: 'AI420', name: 'Evolutionary Algorithm',            credits: 3, sem: '2', prereqs: ['AI320'],        specs: ['AI'],               groups: ['AI_CORE'] },
  { code: 'AI430', name: 'Computational Intelligence',        credits: 3, sem: '2', prereqs: ['AI310'],        specs: ['AI'],               groups: ['AI_CORE'] },
  { code: 'AI435', name: 'Spoken Language Processing',        credits: 3, sem: 'x', prereqs: ['AI360'],        specs: ['AI'],               groups: ['AI_ELECTIVE'] },
  { code: 'AI457', name: 'Knowledge Representation',          credits: 3, sem: 'x', prereqs: ['AI310'],        specs: ['AI'],               groups: ['AI_ELECTIVE'] },
  { code: 'AI460', name: 'Natural Language Understanding',    credits: 3, sem: '2', prereqs: ['AI360'],        specs: ['AI'],               groups: ['AI_CORE'] },
  { code: 'AI490', name: 'Bioinformatics',                    credits: 3, sem: 'x', prereqs: ['AI310'],        specs: ['AI'],               groups: ['AI_ELECTIVE'] },
  { code: 'AI496', name: 'Selected Topics in AI',             credits: 3, sem: 'x', prereqs: [],               specs: ['AI'],               groups: ['AI_ELECTIVE'] },
  { code: 'AI498', name: 'Project',                           credits: 6, sem: '1', prereqs: ['CS251'],        specs: ['AI'],               groups: ['AI_CORE'] },
  { code: 'CS111', name: 'Introduction to Computers',         credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS112', name: 'Programming 1',                     credits: 3, sem: '2', prereqs: ['CS111'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS213', name: 'Programming 2',                     credits: 3, sem: '1', prereqs: ['CS112'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS214', name: 'Data Structures',                   credits: 3, sem: '1', prereqs: ['CS112'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS221', name: 'Logic Design',                      credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS241', name: 'Operating Systems 1',               credits: 3, sem: '1', prereqs: ['CS112'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS251', name: 'Software Engineering 1',            credits: 3, sem: '2', prereqs: ['CS112'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS313', name: 'Programming 3',                     credits: 3, sem: '1', prereqs: ['CS213'],        specs: ['GENERAL'],          groups: ['FACULTY_CHOOSE_3'] },
  { code: 'CS316', name: 'Algorithms',                        credits: 3, sem: '2', prereqs: ['CS214'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'CS322', name: 'Computer Organization',             credits: 3, sem: '1', prereqs: ['CS221'],        specs: ['CS'],               groups: ['CS_CORE'] },
  { code: 'CS342', name: 'Operating Systems 2',               credits: 3, sem: '1', prereqs: ['CS241'],        specs: ['CS'],               groups: ['CS_CORE'] },
  { code: 'CS352', name: 'Software Engineering 2',            credits: 3, sem: '2', prereqs: ['CS251'],        specs: ['CS','IS','IT'],      groups: ['CS_CORE','IS_ELECTIVE','IT_ELECTIVE'] },
  { code: 'CS405', name: 'Theory of Computation',             credits: 3, sem: '2', prereqs: ['MA112'],        specs: ['CS'],               groups: ['CS_CORE'] },
  { code: 'CS410', name: 'Concepts of Programming Languages', credits: 3, sem: '1', prereqs: ['CS112'],        specs: ['CS'],               groups: ['CS_ELECTIVE'] },
  { code: 'CS416', name: 'Advanced Algorithms',               credits: 3, sem: 'x', prereqs: ['CS316'],        specs: ['AI','CS'],           groups: ['AI_ELECTIVE','CS_ELECTIVE'] },
  { code: 'CS419', name: 'Compilers',                         credits: 3, sem: '2', prereqs: ['CS214'],        specs: ['CS'],               groups: ['CS_CORE'] },
  { code: 'CS460', name: 'Distributed Systems and Cloud',     credits: 3, sem: '2', prereqs: ['IT222'],        specs: ['AI','CS'],           groups: ['AI_ELECTIVE','CS_CORE'] },
  { code: 'CS471', name: 'Parallel Processing and HPC',       credits: 3, sem: '1', prereqs: ['CS241'],        specs: ['AI','CS'],           groups: ['AI_ELECTIVE','CS_CORE'] },
  { code: 'CS480', name: 'Cryptography',                      credits: 3, sem: 'x', prereqs: ['ST121'],        specs: ['AI','CS'],           groups: ['AI_ELECTIVE','CS_ELECTIVE'] },
  { code: 'CS496', name: 'Selected Topics in CS',             credits: 3, sem: 'x', prereqs: [],               specs: ['CS'],               groups: ['CS_ELECTIVE'] },
  { code: 'CS498', name: 'Project',                           credits: 6, sem: '1', prereqs: ['CS251'],        specs: ['CS'],               groups: ['CS_CORE'] },
  { code: 'HU111', name: 'English 1',                         credits: 2, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['UNIVERSITY_MANDATORY'] },
  { code: 'HU112', name: 'English 2',                         credits: 2, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['UNIVERSITY_MANDATORY'] },
  { code: 'HU121', name: 'Fundamentals of Economics',         credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['UNIVERSITY_CHOOSE_2'] },
  { code: 'HU122', name: 'Fundamentals of Management',        credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CHOOSE_3'] },
  { code: 'HU313', name: 'Human Rights',                      credits: 2, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['UNIVERSITY_MANDATORY'] },
  { code: 'HU323', name: 'Fundamentals of Accounting',        credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['UNIVERSITY_CHOOSE_2'] },
  { code: 'HU334', name: 'Professional Ethics',               credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['UNIVERSITY_CHOOSE_2'] },
  { code: 'IS211', name: 'Database System 1',                 credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IS231', name: 'Fundamentals of Information Systems',credits:3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IS240', name: 'Operation Research',                credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IS241', name: 'Modeling and Simulation',           credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CHOOSE_3'] },
  { code: 'IS312', name: 'Database Systems 2',                credits: 3, sem: '1', prereqs: ['IS211'],        specs: ['AI','CS','IS','IT'], groups: ['AI_ELECTIVE','CS_ELECTIVE','IS_CORE','IT_ELECTIVE'] },
  { code: 'IS313', name: 'Data Storage and Retrieval',        credits: 3, sem: '1', prereqs: ['IS211'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IS321', name: 'Project Management',                credits: 3, sem: '2', prereqs: ['IS240'],        specs: ['GENERAL'],          groups: ['FACULTY_CHOOSE_3'] },
  { code: 'IS333', name: 'Management Information System',     credits: 3, sem: '2', prereqs: ['IS231'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IS345', name: 'Internet Applications',             credits: 3, sem: '2', prereqs: ['IT223'],        specs: ['IS','IT'],           groups: ['IS_CORE','IT_ELECTIVE'] },
  { code: 'IS350', name: 'Business Intelligence & Analytics', credits: 3, sem: '1', prereqs: ['ST112'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IS351', name: 'System Analysis and Design 1',      credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IS352', name: 'Analysis and Design of IS 2',       credits: 3, sem: '2', prereqs: ['IS351'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IS360', name: 'Introduction to Data Science',      credits: 3, sem: '1', prereqs: ['IS312'],        specs: ['AI','IS'],           groups: ['AI_ELECTIVE','IS_CORE'] },
  { code: 'IS365', name: 'Big Data Technologies',             credits: 3, sem: '1', prereqs: ['IS211'],        specs: ['AI','IS'],           groups: ['AI_CORE','IS_CORE'] },
  { code: 'IS414', name: 'Information System Security',       credits: 3, sem: '1', prereqs: ['IS211'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IS421', name: 'Data Mining',                       credits: 3, sem: '1', prereqs: ['IS211'],        specs: ['IS'],               groups: ['IS_ELECTIVE'] },
  { code: 'IS422', name: 'Data Warehousing',                  credits: 3, sem: '2', prereqs: ['IS211'],        specs: ['IS'],               groups: ['IS_ELECTIVE'] },
  { code: 'IS434', name: 'Quality Assurance of IS',           credits: 3, sem: '1', prereqs: ['IS352'],        specs: ['IS'],               groups: ['IS_ELECTIVE'] },
  { code: 'IS435', name: 'Information Centers Management',    credits: 3, sem: '2', prereqs: [],               specs: ['IS'],               groups: ['IS_ELECTIVE'] },
  { code: 'IS448', name: 'Knowledge Base Management',         credits: 3, sem: '2', prereqs: ['IS312'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IS451', name: 'Decision Support System',           credits: 3, sem: '2', prereqs: ['IS231'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IS496', name: 'Selected Topics in IS',             credits: 3, sem: 'x', prereqs: [],               specs: ['IS'],               groups: ['IS_ELECTIVE'] },
  { code: 'IS498', name: 'Project',                           credits: 6, sem: '1', prereqs: ['IS351'],        specs: ['IS'],               groups: ['IS_CORE'] },
  { code: 'IT111', name: 'Electronics 1',                     credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IT221', name: 'Data Communication',                credits: 3, sem: '1', prereqs: ['ST121'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IT222', name: 'Computer Networks 1',               credits: 3, sem: '2', prereqs: ['IT221'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IT223', name: 'Internet Technology',               credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'IT241', name: 'Signals and Systems',               credits: 3, sem: '2', prereqs: ['MA113'],        specs: ['GENERAL'],          groups: ['FACULTY_CHOOSE_3'] },
  { code: 'IT311', name: 'Computer Architecture',             credits: 3, sem: '1', prereqs: ['CS221'],        specs: ['IT'],               groups: ['IT_CORE'] },
  { code: 'IT312', name: 'Microprocessors',                   credits: 3, sem: '2', prereqs: ['CS221'],        specs: ['AI','CS','IT'],      groups: ['AI_ELECTIVE','CS_ELECTIVE','IT_ELECTIVE'] },
  { code: 'IT321', name: 'Communication Technology',          credits: 3, sem: '1', prereqs: ['IT221'],        specs: ['IT'],               groups: ['IT_CORE'] },
  { code: 'IT322', name: 'Computer Network 2',                credits: 3, sem: '1', prereqs: ['IT222'],        specs: ['IT'],               groups: ['IT_CORE'] },
  { code: 'IT331', name: 'Computer Graphics 1',               credits: 3, sem: '2', prereqs: ['CS112'],        specs: ['CS','IT'],           groups: ['CS_CORE','IT_CORE'] },
  { code: 'IT341', name: 'Digital Signal Processing',         credits: 3, sem: '1', prereqs: ['MA112'],        specs: ['AI','IT'],           groups: ['AI_ELECTIVE','IT_CORE'] },
  { code: 'IT342', name: 'Pattern Recognition',               credits: 3, sem: '2', prereqs: [],               specs: ['CS','IT'],           groups: ['CS_ELECTIVE','IT_CORE'] },
  { code: 'IT414', name: 'Embedded Systems',                  credits: 3, sem: 'x', prereqs: ['IT312'],        specs: ['AI','CS','IT'],      groups: ['AI_ELECTIVE','CS_ELECTIVE','IT_ELECTIVE'] },
  { code: 'IT415', name: 'Robotics',                          credits: 3, sem: '2', prereqs: ['MA112'],        specs: ['AI','IT'],           groups: ['AI_ELECTIVE','IT_ELECTIVE'] },
  { code: 'IT422', name: 'Wireless and Mobile Networks',      credits: 3, sem: 'x', prereqs: ['IT322'],        specs: ['IT'],               groups: ['IT_ELECTIVE'] },
  { code: 'IT423', name: 'Network Security',                  credits: 3, sem: '2', prereqs: ['IT222'],        specs: ['CS','IS','IT'],      groups: ['CS_CORE','IS_ELECTIVE','IT_CORE'] },
  { code: 'IT433', name: 'Multimedia',                        credits: 3, sem: '1', prereqs: ['CS112'],        specs: ['CS','IT'],           groups: ['CS_ELECTIVE','IT_CORE'] },
  { code: 'IT441', name: 'Image Processing 1',                credits: 3, sem: '1', prereqs: ['IT241'],        specs: ['AI','CS','IT'],      groups: ['AI_CORE','CS_ELECTIVE','IT_CORE'] },
  { code: 'IT443', name: 'Speech Processing',                 credits: 3, sem: '2', prereqs: ['IT241'],        specs: ['AI','IT'],           groups: ['AI_ELECTIVE','IT_ELECTIVE'] },
  { code: 'IT444', name: 'Computer Vision',                   credits: 3, sem: '2', prereqs: ['CS316'],        specs: ['AI','CS','IT'],      groups: ['AI_ELECTIVE','CS_ELECTIVE','IT_CORE'] },
  { code: 'IT496', name: 'Selected Topics in IT',             credits: 3, sem: '1', prereqs: [],               specs: ['IT'],               groups: ['IT_ELECTIVE'] },
  { code: 'IT498', name: 'Project',                           credits: 6, sem: '1', prereqs: ['IT222'],        specs: ['IT'],               groups: ['IT_CORE'] },
  { code: 'MA111', name: 'Mathematics 1',                     credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'MA112', name: 'Discrete Mathematics',              credits: 3, sem: '2', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'MA113', name: 'Mathematics 2',                     credits: 3, sem: '2', prereqs: ['MA111'],        specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'PH111', name: 'Physics',                           credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
  { code: 'ST112', name: 'Probability and Statistics 2',      credits: 3, sem: '2', prereqs: ['ST121'],        specs: ['GENERAL'],          groups: ['FACULTY_CHOOSE_3'] },
  { code: 'ST121', name: 'Probability and Statistics 1',      credits: 3, sem: '1', prereqs: [],               specs: ['GENERAL'],          groups: ['FACULTY_CORE'] },
]
